"""Password hashing for Dina.

Passwords are hashed with Argon2id through ``argon2-cffi``'s
``PasswordHasher``. Hashes are stored as PHC-encoded strings, so the cost
parameters (time, memory, parallelism, salt length) travel with the hash and
can be raised later without a schema migration or a password reset mail-out.

Cost parameters follow the OWASP Password Storage Cheat Sheet recommendation
for Argon2id (64 MiB, t=3, p=4) and are named constants here so the policy is
reviewable in one place.

Nothing in this module logs a password or a hash. Callers must treat the return
value of :func:`hash_password` as a credential in transit: it is safe to store
in the database, never safe to print, echo into an API response or audit row.
"""

from __future__ import annotations

from argon2 import PasswordHasher, Type
from argon2.exceptions import Argon2Error, InvalidHashError, VerificationError

# OWASP-recommended Argon2id cost parameters.
ARGON2_TIME_COST = 3
ARGON2_MEMORY_COST_KIB = 65536
ARGON2_PARALLELISM = 4
ARGON2_HASH_LEN = 32
ARGON2_SALT_LEN = 16

#: Passwords longer than this are rejected outright rather than hashed, so a
#: multi-megabyte request body cannot be used to burn CPU/memory on a login.
MAX_PASSWORD_LENGTH = 1024

#: Argon2id, i.e. the hybrid variant recommended by RFC 9106.
_ARGON2_TYPE = Type.ID

_password_hasher = PasswordHasher(
    time_cost=ARGON2_TIME_COST,
    memory_cost=ARGON2_MEMORY_COST_KIB,
    parallelism=ARGON2_PARALLELISM,
    hash_len=ARGON2_HASH_LEN,
    salt_len=ARGON2_SALT_LEN,
    type=_ARGON2_TYPE,
)


class InvalidPassword(ValueError):
    """Raised when a password cannot be hashed under the current policy."""


def _validate_password(password: str) -> None:
    """Reject passwords that must never be hashed.

    Raises:
        InvalidPassword: if ``password`` is empty, whitespace-only, longer than
            :data:`MAX_PASSWORD_LENGTH`, or contains a NUL character.
    """
    if not isinstance(password, str):
        raise InvalidPassword("password must be a string")
    if "\x00" in password:
        raise InvalidPassword("password must not contain NUL characters")
    if not password.strip():
        raise InvalidPassword("password must not be empty")
    if len(password) > MAX_PASSWORD_LENGTH:
        raise InvalidPassword(
            f"password must be at most {MAX_PASSWORD_LENGTH} characters"
        )


def hash_password(password: str) -> str:
    """Hash ``password`` with Argon2id and return a PHC-encoded string.

    The salt is generated by the library and embedded in the result, so two
    calls with the same password produce different strings.

    Raises:
        InvalidPassword: if the password is empty or too long to hash.
    """
    _validate_password(password)
    return _password_hasher.hash(password)


def verify_password(password: str, encoded_hash: str) -> bool:
    """Constant-time check of ``password`` against a stored PHC-encoded hash.

    Returns ``False`` rather than raising for a wrong password, a malformed or
    unparsable stored hash, or a password the policy would refuse to hash. A
    login request must fail closed, never turn a corrupt row into a 500.
    """
    if not isinstance(password, str) or not isinstance(encoded_hash, str):
        return False
    if not password.strip() or len(password) > MAX_PASSWORD_LENGTH:
        return False
    try:
        return _password_hasher.verify(encoded_hash, password)
    except (VerificationError, InvalidHashError, Argon2Error, ValueError):
        # InvalidHashError subclasses ValueError; both are covered above so a
        # corrupt stored hash cannot escape as an unhandled exception.
        return False


def needs_rehash(password: str, encoded_hash: str) -> bool:
    """Return ``True`` when ``encoded_hash`` was made with weaker parameters.

    Callers re-hash the plaintext on the next successful login and store the
    result, which upgrades stored hashes when :data:`ARGON2_TIME_COST`,
    :data:`ARGON2_MEMORY_COST_KIB` or any other parameter is raised.

    The password is verified first, so a wrong password never triggers a
    rehash, and a malformed or unparsable hash is reported as ``False``
    instead of raising.
    """
    if not verify_password(password, encoded_hash):
        return False
    try:
        return _password_hasher.check_needs_rehash(encoded_hash)
    except (VerificationError, InvalidHashError, Argon2Error, ValueError):
        return False
